### ISSUE TITLE
"No Package matching 'bigtop-utils

### ISSUE THREAD

**Issue by sanjaykumarswarnkar** [sergevs/ansible-cloudera-hadoop#4]
TASK [common : install packages] 
error: (item=[u'java-1.8.0', u'bigtop-utils']) => {"changed": false, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["java-1.8.0", "bigtop-utils"], "state": "latest", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "item": ["java-1.8.0", "bigtop-utils"], "msg": **"No Package matching 'bigtop-utils' found available, installed or updated"**, "rc": 0, "results": ["All packages providing java-1.8.0 are up to date"]}

**Comment by sergevs** [comment]
please read the **Requirements** section carefully.
in particular:
"The required for Cloudera Hadoop repositories have to be properly configured on the target hosts"
bigtop-utils package is the part of cloudera hadoop distribution so the repository is not configured properly as it's not possible to install the package
