### ISSUE TITLE
TASK [zookeeper : start zookeeper]

### ISSUE THREAD

**Issue by sanjaykumarswarnkar** [sergevs/ansible-cloudera-hadoop#5]
FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "zookeeper-server", "pattern": null, "runlevel": "default", "sleep": null, "state": "restarted"}, "module_name": "service"}, "msg": **"Job for zookeeper-server.service failed because a configured resource limit was exceeded.** See \"systemctl status zookeeper-server.service\" and \"journalctl -xe\" for details.\n"}

Regarding the java requirement how to download rpm package from CLI in RHEL 7, also after downloading where to keep it?
which limit is this talking about?
I have 8GB ram & 500GB HD vm's for this

**Comment by revolutionisme** [comment]
One workaround I followed to make it work is to comment the following in roles/zookeeper/tasks/main.yml:

- name: start zookeeper
  tags: service
  service: name=zookeeper-server state=restarted enabled=yes

and run the zookeeper server as follows:

- name: start zookeeper
  tags: service
  shell: sudo /etc/rc.d/init.d/zookeeper-server start

But obviously this is not the fix.

**Comment by sergevs** [comment]
I've never experienced problems with that. Probably it would be good to follow:
<"See "systemctl status zookeeper-server.service" and "journalctl -xe" for details.\n"}"> and understand the reason it's failed for your particular case.
BTW, a good issue report must always contain as much information as possible. as an instance software versions( for this particular project is's ansible, hadoop, java, OS ), log extracts.
