### ISSUE TITLE
Can't login to Hue

### ISSUE THREAD

**Issue by revolutionisme** [sergevs/ansible-cloudera-hadoop#6]
After completing the ansible installation, I cannot login to hue. Checked the corresponding database table and found it to be empty. How to log in to Hue or create a login?

Also, How to access the dashboard?

**Comment by newsgate** [comment]
Hue is configured to use PAM authentication so you can access it using an linux account credentials configured on the Hue host by https://\<hue host>:8888 URL.

Dashboard is accessible by http://\<dashboard host>/dashboard URL.

**Comment by revolutionisme** [comment]
I got the dashboard, thanks. Although I still can't login to hue. Tried all the different account credentials on my linux host. Even tried the following link, 

http://gethue.com/password-management-in-hue/

But still nothing. From what I read, the first time I access hue, it should ask to create a user. but I don't get any such prompt.

**Comment by sergevs** [comment]
please take a look on /var/log/hue/access.log and  /var/log/hue/error.log. it should a hint related to the login issue

**Comment by revolutionisme** [comment]
Checked the log files and everything, there's nothing. 

What seems off is that the first time I open hue on a browser it should ask me to create a username and password but it doesn't.

Also the browser keeps on saying that the certificate is invalid.
