### ISSUE TITLE
Error while installing to Centos 7 bigtop-utils not found

### ISSUE THREAD

**Issue by femibyte** [sergevs/ansible-cloudera-hadoop#7]
Hi, I got the following error while trying to install to a Centos 7 machine:

```
TASK [common : install packages] ***********************************************
failed: [10.206.46.222] (item=[u'java-1.8.0', u'bigtop-utils']) => {"changed": false, "failed": true, "item": ["java-1.8.0", "bigtop-utils"], "msg": "No Package matching 'bigtop-utils' found available, installed or updated", "rc": 0, "results": []}
```

**Comment by sergevs** [comment]
Please read documentation "Requirements" section:
"The required for Cloudera Hadoop repositories have to be properly configured on the target hosts"
bitop-utils package is a part of Cloudera Hadoop repository.

**Comment by femibyte** [comment]
So are you saying that bigtop-utils installation on the target host isn't supposed to be handled by your playbook ?

**Comment by sergevs** [comment]
I'm saying : "Cloudera Hadoop repositories have to be properly configured on the target hosts".
If the repository configured properly, the following command should provide a similar output:
```
% yum info bigtop-utils
Name        : bigtop-utils
Arch        : noarch
Version     : 0.7.0+cdh5.9.0+0
Release     : 1.cdh5.9.0.p0.30.el7
Size        : 11 k
Repo        : extras
Summary     : Collection of useful tools for Bigtop
URL         : http://bigtop.apache.org/
License     : ASL 2.0
Description : This includes a collection of useful tools and files for Bigtop

```

**Comment by femibyte** [comment]
Ok, thanks.
